name: 'Tag based on milestone title'
description: 'Tag the repository on pull request merge. Tag name is based on the attached milestone title.'
author: 'swisstopo'
inputs:
  github_token:
    required: true
    description: 'Github repository token'
  custom_tag:
    default: '${MILESTONE}'
    description: 'Custom Tag'
  initial_tag_number:
    default: 1
    description: 'Initial tag number'
  milestone_pattern:
    default: '.+?'
    description: 'Milestone pattern used to search previous tag'
  dry_run:
    default: false
    description: 'Dry run for testing, do not create the tag if set to true.'
outputs:
  new_tag:
    description: 'New tag'
  previous_tag:
    description: 'Previous tag'
  tag_created:
    description: '"true" if a tag has been created, "false" otherwise'
runs:
  using: 'node12'
  main: 'dist/index.js'
