name: PR Auto Edit

# Auto PR Release Title. When creating a Release or Hotfix, the PR title is automatically set.
#
# For new release (develop -> master PR) the title is set to `New Release <next-version> - <bump-type>`
# with bump-type taken from the original title or from the change log commit message.
# By default bump-type if not specified or found is set to minor.
#
# For hotfix (hotfix-* -> master PR) the title is set to `<next-version> - <original-title> - <bump-type>`
#
# Finally add a Label to the PR based on HEAD branch name. These labels are then used to categorize
# the release notes.

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited

jobs:
  pr-edit:
    uses: geoadmin/.github/.github/workflows/pr-auto-semver.yml@master
